site_name: "AI-Enabled Smart Library Management and Resource Recommendation System"
site_url: https://aks1110.github.io/SE_AI-EnabledSmartLibraryManagementSystem

plugins:
  - search
  - literate-nav:
      nav_file: summary.md
  - section-index
  - git-revision-date-localized
  - git-authors
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            summary: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_full_path: true
            show_root_heading: true
            show_source: false

theme:
  name: material
  custom_dir: docs/assets/theme-overrides

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle-outline
    logo: material/library

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to light mode

  logo: assets/tiet-logo.svg
  favicon: assets/favicon.png

repo_url: https://github.com/AKS1110/SE_AI-EnabledSmartLibraryManagementSystem
repo_name: SE_AI-EnabledSmartLibraryManagementSystem

edit_uri: edit/master/docs/

copyright: "Copyright &copy; 2026 Arnav Agarwal, Aradhya Goyal, Amanjot Kaur Sidhu • UCS503P Software Engineering"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AKS1110/SE_AI-EnabledSmartLibraryManagementSystem
      name: GitHub Repository

  generator: false

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - javascript/arithmatex.js

markdown_extensions:
  - abbr
  - md_in_html
  - attr_list

  - toc:
      permalink: true
      toc_depth: 4

  - footnotes

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format
            {which: generic}

  - pymdownx.snippets

  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          arithmatex: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format
            {which: generic}

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - sane_lists
